### ISSUE TITLE
Autofill isn't working on mobile (generally or for a specific site or app)

### ISSUE THREAD

**Issue by eliykat** [bitwarden/android#1389]
## Describe the Bug

We are aware of some situations where the Bitwarden mobile app will not autofill information correctly. This may be due to:
* the particular website or app you're trying to autofill
* the particular browser being used (including first and third party browsers)
* the mobile operating system and/or its version (Android vs. iOS)
* the mobile device (hardware)
* some other combination of factors

This includes situations where:
* autofill does not work at all
* autofill does not work consistently
* autofill otherwise does not work as expected

This is something the Bitwarden team is actively working on but need your help as a community and active Bitwarden users!

Note: this issue is for the **Bitwarden mobile app only**. If you're having issues with the browser extension on a computer, please go to [this issue instead](https://github.com/bitwarden/browser/issues/1621).

## Expected Result

If you have autofill enabled (following the instructions for [Android](https://bitwarden.com/help/article/auto-fill-android/) or [iOS](https://bitwarden.com/help/article/auto-fill-ios/), and you click a field in a login form in your mobile browser or an app, you should have the option to autofill the credentials from your Bitwarden vault.

## Actual Result

This works most of the time, but not always and it can depend on _many, many_ factors. Some sites, apps or devices simply don't work, some don't work consistently and others who knows. This is what we're aiming to fix!

## Call to Action

Below is a link to a Google Form that we have created for capturing information that will help us track down all of these pages, apps, devices and/or OS versions where Bitwarden has failed to autofill your information. You may submit as many as you like, just please help us help you and the community by providing meaningful information and only those sites/pages where it legitimately doesn't work.

[Report autofill failure - mobile](https://forms.gle/NcZ2BmLfKH9txCzz8)

If you've been sent to this issue because another issue you had open was closed as a duplicate, thank you for taking the time to submit the issue to us, however we truly need to track this under a single item in aggregate fashion so we can manage it holistically and ensure we're taking broad measures that will improve this behavior with the maximum benefit to all. Please consider using the linked form above to submit the prior sites you had reported in the issue closed.

**Comment by larena1** [comment]
@eliykat is there any news maybe? It's soon 3 months that "the Bitwarden team is actively working on" fixing the longstanding autofill issues, part of which been reported years ago but never cared about, and the commit history unfortunately does not indicate any progress so far.

**Comment by douglasparker** [comment]
I counted 62 referenced issues.

When my issue was closed this issue didn't even accurately reflect the problem that was described in the original issue.

I will admit, autofill has gotten better but I can't help but feel annoyed that so many people put in effort to help diagnose the problems with autofill only to be swept under the rug.

**Comment by tgreer-bw** [comment]
Hi @douglasparker and @larena1 - thanks for your feedback here. I can confirm that this is an active research endeavor - no code commits yet, as we need to use a scalable and sustainable mechanism for this. We actually have brought additional roles into the engineering realm to assist with many of the autofill/autosave items.

@douglasparker we use the google sheet as a faster way to compare URLs, etc. than within comments on issues.

**Comment by puppykickr** [comment]
As the Auto-Fill 'feature' has never, ever worked at all for me on any of my devices, I just don't use it.
Sure, at first it was very frustrating for me- but once I came to the conclusion that it does not work, will not ever work, and therefore is not really a feature at all- I was relieved of this irritation.

In fact, this is not a Bitwarden problem.
Auto-Fill never worked right for me even before Bitwarden was on any of my devices.

I just use the quick setting tile, and save the info I need to the clipboard (keyboard, not system) and type the other info.

Yes, it is a hassle.
But much less so than trying to get Auto-Fill to work.

**Comment by heiserhorn** [comment]
Is there any time frame to improve the Auto-Fill behavior following the inputs provided in the google doc file?

**Comment by geoffsterr** [comment]
have you considered the possibility of an unknown malware capturing the password to certain apps? It kinda seems like the login details are getting captured in transit from vault to the certain app. I've run lots of scans with many products but well no can detect Pegasus yet only look for traces. I have reason to believe my device has been targeted by someone.

**Comment by douglasparker** [comment]
> I have reason to believe my device has been targeted by someone.

If your device was compromised, all of your accounts would be compromised and you'd be well aware of that by now.

Bitwarden can't protect you from a device that is compromised.

**Comment by geoffsterr** [comment]
hi well it's not quite as simple as that, and I don't recall asking anything about needing protection, I was simply giving the background and a possible area to look at as a cause
I thought was pretty simple to make out without your massive assumptions

**Comment by douglasparker** [comment]
> hi well it's not quite as simple as that, and I don't recall asking anything about needing protection, I was simply giving the background and a possible area to look at as a cause

It's most definitely not malware that is causing the autofill issues.

> I thought was pretty simple to make out without your massive assumptions

Yeah, okay bud. 👍

**Comment by larena1** [comment]
@eliykat @Greenderella 

Another month now and still no traces of any progress to be seen. Would you mind sharing the status with us? Autofill is not an overly complicated feature IMHO. In case of native Android autofill it's just parsing the view structure and feeding the right data back to the system.

For the most part it's working as it is but it'll always fill the password into the username field on sites where there's only a username field like Amazon eBay PayPal Microsoft etc and that there's no fallback in match detection to detect hostname when only the hostname is provided like through native Android autofill APIs but the entry has match detection set to starts with.

**Comment by yurividal** [comment]
On Samsung browser, if you close Samsung browser (recents, swipe up) and relaunch it, bitwarden works and you get the inline autofill. **It works for a while, and then after some minutes it stops again**. So, it's definitely some sort of timer or timeout that is going on, that somehow kills the autofill service for the browser.

**Comment by THEOCKID** [comment]
> @eliykat @Greenderella
> 
> Another month now and still no traces of any progress to be seen. Would you mind sharing the status with us? Autofill is not an overly complicated feature IMHO. In case of native Android autofill it's just parsing the view structure and feeding the right data back to the system.
> 
> For the most part it's working as it is but it'll always fill the password into the username field on sites where there's only a username field like Amazon eBay PayPal Microsoft etc and that there's no fallback in match detection to detect hostname when only the hostname is provided like through native Android autofill APIs but the entry has match detection set to starts with.
==============

I would say that Autofill is a *wildly* complicated feature, depending on 10's of items all working at the same time to have a successfull 'fill.  

Truth be told, I've used bitwarden for years and have loved it.  Recently, I've tried "straying" to other PW managers (e.g. 1password, Keeper).  They have more pleasing interfaces, and I just wanted to see what was out there.  Well, I can tell you I'm back to Bitwarden, and I'll probably "stray" in 3-5 years again to test the waters.

Bitwarden, ,while not perfect, is in my opinion the top in terms of functionality.  With autofill, yes, it doesnt always pop up perfectly, and/or doesn't make the right pick from my vault, BUT I always have the access to BW via the QuickTiles, and can quickly get the Username/Password/TOTP that I need, and those things can't be said for Keeper or 1PW etc.  Those other apps: if they don't get a perfect match with your vault records, pow, you get nothing.  NOTHING.  BW has multiple redundancies / paths at hand.

With BW, I know that I have multiple routes to get my info that i need. It either (a) works and pops up the autofill button and (a1) gives me the correct info or (a2) I can pick from the list of comparable logins or (1c) I can choose to search my entire vault and copy and paste manually OR (b) doesn't pop up and I can (b1) go to the QuickTiles and pick either (b2) Auto-fill or (b3) My Vault and get my info that way (I don't find the Auto-fill quicktile to work that frequently, but I still try it).

I want to thank @kspearrin and @tgreer-bw  et al for their continued improvements with the app, and I've learned to be patient with the process.

**Comment by lucamp** [comment]
Hi,
please do not take this as impoliteness to your team.

[KepassDX](https://github.com/Kunzisoft/KeePassDX) password manager has no issue with autofill in my Android 10 except that it does not copy OTP.
Since it is opensource, do you believe is worth a look how they are doing it?

Thanks

**Comment by yurividal** [comment]
I have recently updated my Samsung Galaxy s21 to android 12 Beta (OneUI 4) and i can confirm that inline autofill has started to work as intended! Seems to work every time, using Samsung browser or chrome. No more timeouts (as of yet. It's been 3 days)

**Comment by larena1** [comment]
More than half a year now and nothing but empty words so far. I was kind of expecting this having seen how issues are being dealt with (or not dealt with at all) in recent years but had a little hope nonetheless.

**Comment by douglasparker** [comment]
Yeah, I was hoping to see some improvements in this area.

Can anyone on the Bitwarden team provide an update?

**Comment by yurividal** [comment]
> More than half a year now and nothing but empty words so far. I was kind of expecting this having seen how issues were being dealt with (or not dealt with at all) in recent years but had a little hope nonetheless.

This seems to be a very complex bug, that involves not only the password manager but also the browsers and maybe even the keyboards.
But, I agree... it is frustrating indeed to have such an issue on a crucial part of the app, and still persist after more than 1 year...

**Comment by larena1** [comment]
> > More than half a year now and nothing but empty words so far. I was kind of expecting this having seen how issues were being dealt with (or not dealt with at all) in recent years but had a little hope nonetheless.
> 
> This seems to be a very complex bug, that involves not only the password manager but also the browsers and maybe even the keyboards. But, I agree... it is frustrating indeed to have such an issue on a crucial part of the app, and still persist after more than 1 year...

It is not that complex at all. It's just that apparently nobody is working on it and that the last official reply was soon 4 months ago.

**Comment by THEOCKID** [comment]
So I got a new Pixel 6 Pro, and had issues, but I've figured out how to get it to work and it hasn't failed me in >2 days (and I use BW a TON!):

# Go into BW on your phone
# Go to Auto-fill Services, and turn off everything:  1st Use Inline Autofill, then Auto-fill Service.  Then Use Draw-Over, then Use Accessibility
# Quit BW
# Close all apps
# Restart phone

Upon restart, run BW and re-enable the 4 options above.

Seems to be working for me.  If needed, before you restart, you could go to Apps (on Android) and open BW and Clear Cache, and could even Clear Data, then restart, then re-enable the 4 options.

Please let me know if this helped.

**Comment by THEOCKID** [comment]
@larena1 pls chill a little.  These guys aren't some big mega-company.  And what does BW cost you? $10 a year?  Let's have some empathy here.

And BTW, I have tried Keeper, having thought of jumping ship from BW.  It's pretty, but also not nearly as functional as BW.  I know, BW isn't for everyone (I'm a function over form guy), but it's pretty solid and I've been using it for .... 6+ years now?

@larena1 pls try my technique above, lemme know if it works for you

**Comment by yurividal** [comment]
> So I got a new Pixel 6 Pro, and had issues, but I've figured out how to get it to work and it hasn't failed me in >2 days (and I use BW a TON!):
> 
> # Go into BW on your phone
> # Go to Auto-fill Services, and turn off everything: 1st Use Inline Autofill, then Auto-fill Service. Then Use Draw-Over, then Use Accessibility
> # Quit BW
> # Close all apps
> # Restart phone
> Upon restart, run BW and re-enable the 4 options above.
> 
> Seems to be working for me. If needed, before you restart, you could go to Apps (on Android) and open BW and Clear Cache, and could even Clear Data, then restart, then re-enable the 4 options.
> 
> Please let me know if this helped.

The this is that, for android 11 and 12,  we should NOT be using Draw over and accessibility. These are legacy methods that do not use the built-in auto-fill api.

Even if this is a workaround, it's not a valid one. The bitwarden team needs to look into what is causing the bitwarden autofill agent to go into sleep.

**Comment by THEOCKID** [comment]
OK, I've given you a method to get it to work, @yurividal .  Maybe BW isn't for you.  Try 1Password or LastPass, see how they work.

@larena1 : I'm not sure how you have determined that "(nobody is) working on it".  @kspearrin and (sorry, forgot the other guys name) are on here all the time.  As above, maybe a diff PW manager would be better for you.  Putting negativity on this site may make you feel better, but it's really doing nothing to forward the cause for BW.  

let's buck up, campers.  If you wanna help, help.  If you wanna complain, then be pleasant/positiive, or just shove off.

**Comment by heiserhorn** [comment]
I personally stopped using BW because of the Android performance. Inline Autofill not working reliably. Some  sites not recognized at all. I appreciate the workarounds but satisfying my needs at the moment. Will come back in the future to see where we stand on this.

**Comment by olfek** [comment]
@heiserhorn What are you using instead? I'm planning to do the same.

**Comment by heiserhorn** [comment]
@olfek I am trying a few and have not decided yet.

**Comment by julian-alarcon** [comment]
I found a workaround for Firefox here
https://github.com/mozilla-mobile/fenix/issues/20987#issuecomment-904772802

Workaround for this:
1- tap to password area
2- press to three dot to open Firefox menu
3- press outside of menu to close it

Also, there is bugzilla report https://bugzilla.mozilla.org/show_bug.cgi?id=1693152

This is also reported in issue https://github.com/bitwarden/mobile/issues/1479

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
https://myid.telstra.com/identity/as/authorization.oauth2?redirect_uri=com.telstra.mobile.android.mytelstra%3A%2F%2Foauth2redirect&client_id=mytelstra-mobile-android&response_type=code&prompt=login&state=jh7Hle0JfHGCCk5S3YuT4g&scope=openid%20app.mytelstra.mobile%20m2w&code_challenge=Ppa1bnRLC6Ei9ig_rmWTooxv6BurGm-V_PccX-SGnlE&code_challenge_method=S256

The Username box does not get detected by Bitwarden at all until you enter the username, and then tap continue to reveal the password box.

**Comment by novocaiin** [comment]
> OK, I've given you a method to get it to work, @yurividal . Maybe BW isn't for you. Try 1Password or LastPass, see how they work.

I don't want to give all my passwords to yet another party.

**Comment by huangtaizia** [comment]
When I open encrypted pdf file by pdf viewer of Google Drive, the BW dialog is appeared and closed immediately, cannot taps on to open BW to select the password saved. I thinking about that BW dialog cannot draw-over any dialog of the others application

**Comment by toxic0berliner** [comment]
I find autofill generally works unless for the sites where I changed the url comparison method to "exact". Can maybe someone look into it, I don't know how to check if the browser passes à wrong url, or if bitwarden isn't able to do the comparison, but I have confirmed that the url is exactly the same but bitwarden isn't showing the item as result.
Even searching manually in bw app it doesn't check. My url is set to exact and looks like https://organizr.example.com/#mytab
Works perfectly in Firefox extension on windows but not in the android app

**Comment by douglasparker** [comment]
It feels like autofill is only getting worse with each major update to Android...

It's working less than half of the time for me on my Samsung Galaxy S21 Ultra running Android 12.

**Comment by larena1** [comment]
> It feels like autofill is only getting worse with each major update to Android...
> 
> It's working less than half of the time for me on my Samsung Galaxy S21 Ultra running Android 12.

Did you give other apps a try to see if the issues are specific to Bitwarden or your device / OS?

But yeah it's been more than 9 months since the big announcement that they're actively working on autofill and yet results still remain to be seen and there has been radio silence for more than six months already.

**Comment by THEOCKID** [comment]
I've been a huge bitwarden proponent, but even I am finally getting tired of manually filling fields.  Sorry, it's become a pain in the ass. So I'm going back to trialing Keeper and 1password.  Maybe BW is more focused on their commercial/enterprise customers. Not sure.  Hell, I'm not even sure they're reading GitHub comments.    #disappointed

**Comment by douglasparker** [comment]
> > It feels like autofill is only getting worse with each major update to Android...
> > 
> > It's working less than half of the time for me on my Samsung Galaxy S21 Ultra running Android 12.
> 
> Did you give other apps a try to see if the issues are specific to Bitwarden or your device / OS?

I took a look at 1Password again, and the autofill API works flawlessly every time.

It works so well that I've barely used my annual family subscription with Bitwarden, and I am eager to migrate over right away.

> But yeah it's been more than 9 months since the big announcement that they're actively working on autofill and yet results still remain to be seen and there has been radio silence for more than six months already. 

Yeah, I didn't realize how bad autofill had gotten with Bitwarden until I gave 1Password a try again.

The level of support by the Bitwarden team has been horrible, too. The lack of communication speaks for itself.

I'm also a huge Bitwarden supporter. I self host Bitwarden as well, and as much as I love open source software, I can't continue to support software that is broken on a fundamental level.

I'm sure that I am far from being the only one who is sick and tired of switching apps to log in to services.

**Comment by vvolkgang** [comment]
Hey everyone! We recently made some improvements to the Android Accessibility Service fixing issues that previously impacted our autofill functionality, it's included in our [recent release](https://github.com/bitwarden/mobile/releases/tag/v2.16.1), currently in each platform store reviewing process.

We failed to communicate that here and for that I'm truly sorry. The team has been actively looking for ways to improve Autofill in Android, some of the ideas we tried failed to accommodate the whole range of Android versions + devices we support but, just wanted to let everyone know that we're still going at it and trying to improve. 

Thanks for your feedback and support, let me know if the new release improves this.

**Comment by THEOCKID** [comment]
this may be a case of too little too late.   I tried Keeper, eh, not great, but 1 Password seems to be fitting the bill.  Autofill actually works (shocking!).  GUI superior as well.  I actually upgraded to their business version as it allows multiple 2FA yubikeys (The basic version allows for a TOTP and a physical key).

Dang BW.  It's been a long ride.  I'll check back in a year or so.

**Comment by yurividal** [comment]
> Hey everyone! We recently made some improvements to the Android Accessibility Service fixing issues that previously impacted our autofill functionality, it's included in our [recent release](https://github.com/bitwarden/mobile/releases/tag/v2.16.1), currently in each platform store reviewing process.
> 
> We failed to communicate that here and for that I'm truly sorry. The team has been actively looking for ways to improve Autofill in Android, some of the ideas we tried failed to accommodate the whole range of Android versions + devices we support but, just wanted to let everyone know that we're still going at it and trying to improve.
> 
> Thanks for your feedback and support, let me know if the new release improves this.

Does this mean we need to use the accessibility service? Its supposed to be a legacy method, replaced by the autofill API since Android 11

**Comment by larena1** [comment]
https://github.com/bitwarden/mobile/commits/master/src/Android/Autofill

Looking at the history, apart from adding new browsers' app ids to the list of supported browsers, there is only 1 PR that included functional changes of autofill handling.

https://github.com/bitwarden/mobile/commit/52024109f7bfd6ae36c6273d03076242c99fd63f

And that does only affect the save prompt for credentials so there seem to be no improvements at all to reliability and quality of autofill itself unfortunately.

**Comment by JoshuaGloriod** [comment]
You guys probably already know, but I've found all troubles with Bitwarden went away with following DKMA's recommended settings. Mentioning just in case.

As seen in this issue https://github.com/urbandroid-team/dont-kill-my-app/issues/307#issue-837495424

I still have the mentioned problem with fields, but Bitwarden now does recognize when it should autofill now. I've looked into that a bit, but not confident on the exact reason yet.

**Comment by bill-mcgonigle** [comment]
This has been bugging me for a long time (Android 11, LineageOS) and by following a few threads here I believe I have isolated my problem to "Battery Manager". After turning it off I don't have to constantly relaunch Bitwarden to get autofill.
![Screenshot_20220316-170220_Settings~2](https://user-images.githubusercontent.com/880256/158690883-b9efc871-9622-463d-9335-f07b7fc48aa2.png)

I do not see Bitwarden using even 1% of the battery in the usage stats (it's too low to show up) so I don't know /why/ it was getting killed. If there's something that could be done programmatically or in the manifest to avoid being reaped by Battery Manager that might help. In theory I should not have to turn it off to use Bitwarden—one presumes that feature isn't fundamentally incompatible with autofill services.
n.b. I already had Bitwarden set to 'not optimized' so this is something different.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
iodé Browser does not autofill as it should.
com.iode.firefox

**Comment by syed-ammar** [comment]
I had the problem for Spotify and Formula1 android app. Enabling Accessibility worked for Spotify app, but for Formula1 it is asking me to create new item even though i have that in my list

**Comment by brotaxt** [comment]
> This has been bugging me for a long time (Android 11, LineageOS) and by following a few threads here I believe I have isolated my problem to "Battery Manager". After turning it off I don't have to constantly relaunch Bitwarden to get autofill. ![Screenshot_20220316-170220_Settings~2](https://user-images.githubusercontent.com/880256/158690883-b9efc871-9622-463d-9335-f07b7fc48aa2.png)
> 
> I do not see Bitwarden using even 1% of the battery in the usage stats (it's too low to show up) so I don't know /why/ it was getting killed. If there's something that could be done programmatically or in the manifest to avoid being reaped by Battery Manager that might help. In theory I should not have to turn it off to use Bitwarden—one presumes that feature isn't fundamentally incompatible with autofill services. n.b. I already had Bitwarden set to 'not optimized' so this is something different.

This is exactly what I did and I couldn't recognize most of the issues that were reported here.

**Comment by THEOCKID** [comment]
Hey! Laughing at myself cause the recent post got me to look at Settings:Apps:Bitwarden:Battery and lo and behold ... I wasn't unrestricted!  Damn you Samsung!  Now I fixed it and will see how it goes!  Thanks everyone!

**Comment by THEOCKID** [comment]
Hey! Laughing at myself cause the recent post got me to look at Settings:Apps:Bitwarden:Battery and lo and behold ... I wasn't unrestricted!  Damn you Samsung!  Now I fixed it and will see how it goes!  Thanks everyone!  
![3414](https://user-images.githubusercontent.com/54771478/161379496-630a631f-7402-4f09-a10a-8b04e84e10fb.jpg)

**Comment by douglasparker** [comment]
For what it’s worth, that didn’t fix it for me either. I always disable battery optimization for Bitwarden the moment I get a new phone and the issues persist.

I just switched to iPhone and all of my issues have been resolved. I’m not longer interested in dealing with bugs with the autofill API.

Google seems to ignore major bugs in their issue tracker for years. I’m a huge android fan but I’ve recently made the decision to completely switch ecosystems.

**Comment by novocaiin** [comment]
Will this ever be resolved in Chromium?

**Comment by uOOOO** [comment]
After upgrading Android 12, autofill doesn't work properly. In many cases, only one of password or username is filled. The device is Galaxy S20+.
e.g. https://play.google.com/store/apps/details?id=com.fineapp.yogiyo&hl=en&gl=US

**Comment by shalom06** [comment]
Ive been having the same issue with the Instagram app for android . It just auto-fill's the username and not password.

**Comment by SoyDiego** [comment]
On mobile on the website [Idea](https://www.idealista.com/login) bitwarden have been written my password in USERNAME.
I tried with linked custom fields but same. The problem is ON MOBILE, in desktop works perfectly.

**Comment by digideth** [comment]
So auto filling password into username field is never going to be fixed???  I've tried custom fields and still doesn't work.

**Comment by dbosompem** [comment]
Hi all, apologies for the inconveniences caused. The team is keeping tabs on this issue and we'd get it fixed, as we keep you in the loop. Thank you for your patience.

**Comment by shaulgo** [comment]
Isn't there a general way to allow custom fields to work on android. If lastpass can find the field then it's technically possible.

**Comment by RafailFridman** [comment]
Autofill not working (no popup, no inline suggestion) in Binance and Bybit apps on Poco X3 NFC
Bitwarden version 2022.8.0

**Comment by abda11ah** [comment]
Also Stargon Browser does not autofill as it should.
net.onecook.browser

**Comment by digideth** [comment]
espn.com doesn't work at all. No logins are even offered in chrome. Can't even test Autofill.

**Comment by smtgpm** [comment]
Hi
For me auto fill also has been getting worse. Latest issue, the service itself keeps turning off (I do not have battery optimization for BW). And even when the service is on, it never proposes auto fill anymore on any site, I first have to open BW, connect, go back to the site and then it'll suggest (sometimes) autofilling. Paypal.com never works though

**Comment by rizi** [comment]
I experience more or less the same issue on Chrome or FireFox using Android 13 on my Pixel 6a

Steps to reproduce
Be sure your Android Bitwarden app is locked *and killed. (i.e. If you open the app, it should prompt you for master password or biometric auth; if it does so, that's good -- leave it in that state, and kill the app by swiping it offscreen from your app-switcher UI). In the event you've unlocked it, lock it via its "Settings|Lock Now" button, and then kill the app.


In Chrome, visit some site where Bitwarden has a saved login that you could use.

Tap the website's username field

Keyboard will appear, with a "Bitwarden Vault is locked" button at the top. Tap that button.

Authenticate with Bitwarden. It will probably then say "Items for mozilla.org" (or whatever site you're on).

Tap its entry for the credentials that you want to use. (This makes Bitwarden disappear and Chrome becomes foreground again.)

Expected behaviour
The username/password field should have been filled in.
Also, my keyboard should have buttons for the various matching logins in Bitwarden, now that I've unlocked it. (This is what happens if I reload at this point and focus the username or password field, i.e. if I perform the STR with Bitwarden already focused.)

Actual behaviour
The username field is still empty.
The password field is also empty.
Open the vault and choose the item again fills the user and the password field, so it works after the second attempt (maybe because the vault is already unlocked)

Device name
Google Pixel 6a

Android version
Android 13


Details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1770010

It's not always but most of the time, it seems all websites are affected (e.g GitHub, Netflix, NCrunch ...), But sometimes its working.

**Comment by supermansaga** [comment]
The following two apps 1) Wechat by Tencent 2) Visible on Android 13 of Google's Pixel 7 Pro don't have auto fill, despite I believe I have enabled them. Should we just give these two apps bad reviews? Instead of being critical of Bitwarden which has been great on iOS? Many thanks.

**Comment by swamp2** [comment]
Etrade App on Android 13 does not support Autofill nor provide an option to memorize the login info.

**Comment by kuxv** [comment]
"Můj vlak" app does not support filling in credit card details on Lineage OS 19. It does not offer option to autofill. I've also tried it with pCloud Pass and that offers the option to fill in the credit card info.

**Comment by digideth** [comment]
Half broken on login.aol.com won't recognize the user name field is on the page. If you know your username and get to the next page it will fill the password.

**Comment by kurczynski** [comment]
> Half broken on login.aol.com won't recognize the user name field is on the page. If you know your username and get to the next page it will fill the password.

FWIW this also happens when trying to log in to [redhat.com](https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/auth?response_type=code&client_id=https%3A%2F%2Fwww.redhat.com%2Fwapps%2Fugc-oidc&redirect_uri=https%3A%2F%2Fwww.redhat.com%2Fwapps%2Fugc%2Fsso%2Flogin&state=41fa133d-3a3e-4d16-859e-f3cf0266b5ab&login=true&scope=openid) on both mobile and desktop.

**Comment by larena1** [comment]
@digideth @kurczynski could you verify if you experience the same issue also with other popular password management apps or if it works correctly? If the latter, there might be a chance for this to be fixed if Bitwarden maintainers look into it.

**Comment by kurczynski** [comment]
@larena1 I don't have any other password management apps, but I assume this is caused by Bitwarden not recognizing the field as a login because there is no password field displayed yet. Not sure if the password field isn't generated until a username is given or if it's just labeled differently in the DOM.

**Comment by digideth** [comment]
@larena1 It should not matter if this happens on the password apps! Bitwarden is broken and they should fix their app

**Comment by larena1** [comment]
@digideth I agree with you, but, as you can see, despite countless complaints and reports over the years, nobody from Bitwarden is looking into it. Their focus seems to be on enterprise features rather than on proper core functionality and UX.

@eliykat Are there any results yet from you actively looking into fixing autofill issues on Android or mobile in general for almost two years? It seems nothing has changed so far and compared to others like LastPass, Enpass or 1Password, Bitwarden still has one of the poorest autofill implementations.

**Comment by eliykat** [comment]
Hi @larena1, I created the issue but I'm not a mobile dev, so I'm not much help here. I've raised your question internally to see if anyone can provide an update.

**Comment by digideth** [comment]
@eliykat thank you! 

I've given up and started to test others again and tbh chrome is leading the pack as far as working correctly all the time for websites...

**Comment by streetwolf** [comment]
Just about every site doesn't autofill for me.  One thing I didn't notice before is that on one site when I bring up the KB to enter my userid one of the KB suggestions is the BW entry for the site. This URL listed is the app I use to get to the site not through a web browser.  Clicking on that fills in the userid/pw.  I've only seen this on one site so far.

**Comment by xyxzxyz** [comment]
@streetwolf same here, unfortunately. Now even on Microsoft login page, autofill doesn't work properly anymore. It filled password into username field and has been behaving like this more commonly.

**Comment by johnebs** [comment]
Recently switched to Bitwarden and just came up with this issue  I consider it to be unacceptable that 9 months after the initial (known) report, the issue is still present. Having the password manager auto populate the password into none password fields is a security risk. Bitwarden sould NOT populate the password if its not confident that the field is a password field.

My dad uses Outlook.com and I was surprised to see Bitwarden freely populating the password in plain text into the email field. This field get catched and now his keyboard has it stored as a valid auto complete text. Huge security risk. This needs to get fixed ASAP. My confidence in the product has gone way down. 9 month... unacceptable, specially for such an easy fix.

If FIELDID <> password then Populate email o Nothing...

**Comment by larena1** [comment]
9 months? This was reported more than 3 years ago. Truth is nobody from Bitwarden cares at all.

https://github.com/bitwarden/mobile/issues/640

**Comment by johnebs** [comment]
> 

Well... I stand corrected and it's way worse that I thought then...

**Comment by THEOCKID** [comment]
Ok everyone here's the real problem.

Go try the competitors.  Or just take my word for it as I've tried 1password, keypass, LastPass, Keeper, etc.  And I found them all lacking compared to bitwarden when it comes to flexibility in password entry.  

For instance, I'll go to a website and unless the URL in the pw manager matches exactly, you're Fd.  Won't fill anything.  With bitwarden you always have the option to pick a near match.   And it's way more flexible for mtille matches.  Example Gmail.  I've got 20 or more emails and it's relatively easy to pick from a list of them in BW, not so in others.  


I know their auto fill has always been problematic.  But try the others and see how it goes.  I'm sorry, I know the others UX is better looking etc and BW hasn't really changed in years.  But I'm a function over form kinda guy, and I'll jump ship when the others do as good.

**Comment by douglasparker** [comment]
I’ve been on Android most of my life, but there seems to be major bugs with the Android autofill API that Google ignores. I believe there are numerous bug reports that have been unresolved for years.

I left Android for Apple last year and I no longer have any issues. I still miss Android but there were so many little bugs and annoyances that no longer exist after switching to Apple.

It’s a shit situation all around and it sucks that the Bitwarden team just ignores the problem and everyone here.

Nobody should have to abandon Android for a stable experience, but here we are. 😩

**Comment by johnebs** [comment]
> 
As a matter of fact I decided to star using Bitwarden because it appeared to be very secure and I'm very pro FLOSS software (even though I'm a paying Bitwarden customer). I've been a LastPass user for years, then tried 1Password for a few months and KeePass for a few days. While the AutoFill has always been problematic (as in not alway working), none of them had the issue of placing the password in any field other than the Password field.

This is an issue exclusive to Bitwarden (to my knowledge). The issues should not be categorized as an inconvenience since it's also a security issue. You can assume that any field other than the password field is not secure. Placing the password on any non password field opens the password to snooping, caching/loging. Nobody should be 'fine' with that bug still active after so many years.

**Comment by larena1** [comment]
I looked into this now.

On https://www.paypal.com/signin Bitwarden will falsely detect the email field as a password field because it has TYPE_TEXT_VARIATION_PASSWORD. The field also has TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS, so it obviously is not a password field. 

Also according to the official documentation, password fields should be tested against TYPE_CLASS_TEXT | TYPE_TEXT_VARIATION_VISIBLE_PASSWORD.

https://developer.android.com/reference/android/text/InputType

The issue can definitely be fixed and it's absolutely devastating that nobody from team Bitwarden ever cared to look into this further in more than 3 years.

**Comment by SergeantConfused** [comment]
We apologize for any confusion we may have caused regarding the tracking mechanism we were using for reporting Autofill issues on Mobile. We were relying on a form submission we track separately as mentioned in the original post. We have created a few new specific GitHub issues for sites recently reported and we will track these individually in GitHub until we determine the best way for Autofill issues to be reported going forward. We appreciate your understanding and we will work with the Engineering team to get these issues resolved.

https://github.com/bitwarden/mobile/issues/2315
https://github.com/bitwarden/mobile/issues/2316
https://github.com/bitwarden/mobile/issues/2318
https://github.com/bitwarden/mobile/issues/2319

**Comment by larena1** [comment]
@SergeantConfused could you also track https://github.com/tutao/tutanota/issues/4499 in separately as another Bitwarden specific autofill issue?

**Comment by SergeantConfused** [comment]
> @SergeantConfused could you also track [tutao/tutanota#4499](https://github.com/tutao/tutanota/issues/4499) separately as another Bitwarden specific autofill issue?

Sure thing (https://github.com/bitwarden/mobile/issues/2323).

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1389
