### ISSUE TITLE
F-Droid - Error Installing Bitwarden

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [bitwarden/android#2187]
### Steps To Reproduce

1. Add the Bitwarden repo in F-Droid.
2. Refresh repositories in F-Droid.
3. Search for and install the latest version of Bitwarden from F-Droid.

### Expected Result

Bitwarden is installed.

### Actual Result

An error is thrown, which reads, "Error installing Bitwarden", "Failed to install due to an unknown error".  The only option to proceed is "OK".

### Additional Context

I've deleted and re-added the Bitwarden repo several times and rebooted the device multiple times.

I'm running GrapheneOS, Android v13, F-Droid v1.15.3, and I'm experiencing the issue in the Owner profile (I have not tried to reproduce this in other android user profiles.

### Operating System

Android

### Operating System Version

13

### Device

Google Pixel 4a

### Build Version

2022.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Silejonu** [comment]
Same issue here on a clean GrapheneOS profile through the Play Store.

**Comment by Xstoudi** [comment]
Same issue on clean GrapheneOS install with Google Pixel 6a.

**Comment by Silejonu** [comment]
> Same issue on clean GrapheneOS install with Google Pixel 6a. Did someone found a workaround?

I successfully installed it on GrapheneOS on a Pixel 6a through F-Droid.

**Comment by Xstoudi** [comment]
Seems to work today!

**Comment by shrimprugbysnowowl** [comment]
Reattempted the installation and nothing has changed on my end. I even deleted and recreated the Bitwarden repo.

**Comment by jcz1** [comment]
"...apk failed to verify!" :(
version 2022.10.1
LineageOS 19 + microG

**Comment by mp-bw** [comment]
I just installed our latest 2022.11.0 release through F-Droid 1.15.4 without issue.

> Does anyone know if an appropriate workaround would be to install the apk hosted here on github?

The F-Droid APK (listed alongside the others) is the same one installed through F-Droid (free from analytics, etc.).

**Comment by jcz1** [comment]
> @jcz1, @catfluoride, @shrimprugbysnowowl Is this still occurring with 2022.11.0 which can be pulled from https://mobileapp.bitwarden.com/fdroid/ ? ([Repo info](https://mobileapp.bitwarden.com/fdroid/repo/))
> 

It is the same. But i am able to install f-droid apk from github...

**Comment by mp-bw** [comment]
> Thank you for the info. Confirming that the Bitwarden F-Droid APK does not check github for an updated APK and notify the user, correct?

@shrimprugbysnowowl That's correct, there's no version checking built-in to the app itself.  However the signing key we use is unique for the F-Droid build so the F-Droid app can still take "ownership" of it and prompt for updates in the future.

**Comment by 8473795** [comment]
Is there any plan/update/eta on this?

It's very difficult to trust my entire password vault to an app that can't be verified!

**Comment by mp-bw** [comment]
This may be connected but I'll leave this issue open until the change goes live.

**Comment by cyanide699** [comment]
Not sure if related but just had an update prompt for bitwarden on fdroid.... It fails to.install "error installing, failed to verify"

**Comment by mp-bw** [comment]
@cyanide699 Looking into this now

**Comment by cyanide699** [comment]
> @cyanide699 Looking into this now

Thanks .. My bw is running ok after the manual upgrade using the apk from github

But just checked fdroid again "check for updates" and still see the index.jar warning about bw.

It does have some numbers about the index.jar
1670237786←16734297
If that helps

**Comment by mp-bw** [comment]
@cyanide699 Should be fixed now (cache problem on our end presented the new apk hash for the old apk resulting in a validation error by the FD client)

**Comment by cyanide699** [comment]
> @cyanide699 Should be fixed now (cache problem on our end presented the new apk hash for the old apk resulting in a validation error by the FD client)

Seems ok here fdroid check for updates shows no warning now (however i had already manually updated)
Thanks for the update!

**Comment by mp-bw** [comment]
I believe there were two separate issues reported in this thread (the first being the cache issue when a new release is pushed, and the second being the improper url).  At the moment both of these have been fixed, however **you may need to remove and re-add the Bitwarden repo to make sure you're using the fixed url**.  Can everyone confirm if that fixes the remaining install issues using the F-Droid client?  (1.15.x or 1.16-alphax are both working for me now).

**Comment by shrimprugbysnowowl** [comment]
> I believe there were two separate issues reported in this thread (the first being the cache issue when a new release is pushed, and the second being the improper url). At the moment both of these have been fixed, however **you may need to remove and re-add the Bitwarden repo to make sure you're using the fixed url**. Can everyone confirm if that fixes the remaining install issues using the F-Droid client? (1.15.x or 1.16-alphax are both working for me now).

Correct, these are separate issues.

I re-added the repository in fdroid but I still receive the same error that I posted about originally - "Error installing Bitwarden[.] Failed to install due to an unknown error".

**Comment by mp-bw** [comment]
@shrimprugbysnowowl Can you confirm the new repo url ends with `/repo`? (full url is `https://mobileapp.bitwarden.com/fdroid/repo`)

**Comment by shrimprugbysnowowl** [comment]
Yes, it ends in ```/repo```.  I copied the link and fingerprint from Bitwarden's website, and it's ```https://mobileapp.bitwarden.com/fdroid/repo```.

**Comment by mp-bw** [comment]
Okay thanks, looks like this issue will unfortunately remain open until we figure out what's going on (but hopefully remain on topic since the other issues described have been fixed)

**Comment by shrimprugbysnowowl** [comment]
Attempted again but the issue remains.  I currently have over 30 other apps installed from f-droid and haven't run into this issue before.  Can someone please update as to the status?  #2276 has not fixed this issue as the header might suggest.

**Comment by shrimprugbysnowowl** [comment]
Can anyone provide an update on this aged issue?  Is there any reason why the app isn't simply included in f-droid's repo if it doesn't have firebase?

**Comment by mpbw2** [comment]
@shrimprugbysnowowl Unfortunately I still have no idea what the problem could be.  I just did a fresh install of F-Droid 1.17.0 and it installed v2023.7.0 without issue.  I'm hoping someone else can provide some insight.

**Comment by shrimprugbysnowowl** [comment]
@mpbw2 , Is there a reason why Bitwarden isn't included in the f-droid repo?

**Comment by shrimprugbysnowowl** [comment]
> the signing key we use is unique for the F-Droid build so the F-Droid app can still take "ownership" of it and prompt for updates in the future.

This appears to be a valid workaround for the time being.  For those having this issue, you can download the latest release of com.x8bit.bitwarden-fdroid.apk and bw-fdroid-apk-sha256.txt (For those using multiple profiles, download this in the owner profile).  Use Termux to verify the checksum.  If it checks, install the apk.  (It would be nice if these releases were signed.  Termux can use gpg, too.)  Install as needed for multiple users.

The only caveat is that you can't install bitwarden-fdroid if you have the play store version installed as they are conflicting packages, even in a different user profile.

**Comment by emielpopla** [comment]
> The only caveat is that you can't install bitwarden-fdroid if you have the play store version installed as they are conflicting packages, even in a different user profile.

I had the same unknown error issue and this seemed to be what was causing it. I had the play store version installed in my work profile. Simply uninstalling it fixed it for me and I could just install the f-droid version without a problem after that.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2187
