### ISSUE TITLE
Password autofill doesn’t work on iOS

### ISSUE THREAD

**Issue by TyphoonFL** [bitwarden/android#3225]
### Steps To Reproduce

1. In safari, Go to a website login page with a stored password in BW
2. Ios keyboard pops up with detected password autofill option
3. Tap on the option to fill with stored PW
4. Password field remains empty 

### Expected Result

Password is filled in

### Actual Result

Password doesn’t fill and remains empty

### Operating System

iOS

### Device

iPhone 13

### Build Version

2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TheRealClarity** [comment]
Can reproduce, iOS 15.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Could you confirm the version of iOS you have installed, and if all websites appear to be affected?

Thanks!

**Comment by NextFire** [comment]
2024.4.2 on iOS 16.7.7, autofill suggestion doesn’t work anymore. 

Video recording on https://mobile.free.fr/account/ below:

https://github.com/bitwarden/mobile/assets/20094890/6a5e2897-df4e-48be-9aa5-7bd3b626043b

**Comment by pheiduck** [comment]
I had to re-enable it. Only auto copy totp is not working iOS 17.4.1

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. Could you all please detail your [KDF configuration](https://bitwarden.com/help/kdf-algorithms/)? I ask because it sounds like you could be encountering [this](https://github.com/bitwarden/mobile/issues/2389).

Thank you in advance,

**Comment by pheiduck** [comment]
Yep, argon2id on my side.

**Comment by NextFire** [comment]
PBKDF2 SHA-256 @ 600000 iterations

**Comment by dazzah87** [comment]
Experiencing the same issue as everyone else in this issue. It started happening after installing the latest update (v2024.4.2). I'm on an iPhone 15 Pro, iOS 17.4.1. I'm currently using the Argon2id KDF algorithm with 4 KDF iterations and 48 MB KDF memory.  KDF parallelism is set to 4.

**Comment by micahblut** [comment]
Thank you all for the reports. We have a fix in place that will be included in an upcoming release. You can track the progress of that fix [here](https://github.com/bitwarden/mobile/pull/3230).

**Comment by mbaran5** [comment]
Has this been released into the AppStore version that was just updated? myself and others are still having this issue even with today's new release. https://www.reddit.com/r/Bitwarden/comments/1csdho7/ios_auto_fill_not_working/l4fobia/

**Comment by Machou** [comment]
So with this morning's update (Version 2024.5.1) the bugs seemed to have been fixed.

I've just retested with the applications I'm 100% sure didn't work 2 days ago, and now I've got no worries, it's back to the way it was before.

Maybe update iOS to 17.5 ? an update appear today.

**Comment by mbaran5** [comment]
I am on 17.5, but what's weird is that AppStore says my app is up to date but the app version was 2024.4.2. When I force killed it and went back to AppStore it prompted an update. So far this seems to be good.

**Comment by 4rtz1z** [comment]
i'm on iOS 16.5 and 16.6.1 latest 2024.5.1 still has the bug, the only version that works on me is 2024.4.0, hope this could be fixed, as this really bad for functionality

**Comment by LunarLanding** [comment]
I am on 2024.5.1, ios 17.5 does not autofill inside apps (from longpress on text field->autofill, only shows icloud), but does autofill inside safari.

**Comment by pheiduck** [comment]
Yes, it is still present on Version: 2024.5.1 (7674)
iOS: 17.5
iPhone 12

**Comment by albertdick** [comment]
Same here.
Cannot autofill username and password.
Tapping on the button nothing happens like the video above.

iPhone 7
iOS 15.8.2
Bitwarden App version 2024.5.1 (7674).

**Comment by LunarLanding** [comment]
It seems the above mentioned fix was merged and will be in version 2024.5.2; currently the AppStore is at the previous one, 2024.5.1. Fingers crossed!

**Comment by 4rtz1z** [comment]
> It seems the above mentioned fix was merged and will be in version 2024.5.2; currently the AppStore is at the previous one, 2024.5.1. Fingers crossed!

Kinda doubt that, i tried the auto build and the issue still persist

**Comment by micahblut** [comment]
Hi all, we expected this to be fixed in 2024.5.1, so if you continue to see the issue please do log your details here. Things like iOS version and how you have configured your autofill settings will help us track this down. Thank you!

**Comment by 4rtz1z** [comment]
iOS 16.5 and 16.6.1
iPhone 13 Pro Max

setup like this :
![IMG_0438](https://github.com/bitwarden/mobile/assets/15857763/87c00c23-c29d-4fd0-8aa3-832af4cf72c4)


here's fail in action :

https://github.com/bitwarden/mobile/assets/15857763/5203f2be-e231-4b54-b543-d32f0fddccca

**Comment by Machou** [comment]
> iOS 16.5 and 16.6.1
> 
> iPhone 13 Pro Max
> 
> setup like this :
> 
> ![IMG_0438](https://github.com/bitwarden/mobile/assets/15857763/87c00c23-c29d-4fd0-8aa3-832af4cf72c4)
> 
> here's fail in action :
> 
> https://github.com/bitwarden/mobile/assets/15857763/5203f2be-e231-4b54-b543-d32f0fddccca
> 
> @micahblut 

iOS 17.5.1
Bitwarden 2024.5.1

All work perfectly :)

![image](https://github.com/bitwarden/mobile/assets/1043650/e57e0097-fc47-485e-8590-411995df0d86)

https://github.com/bitwarden/mobile/assets/1043650/df05faa8-1476-4a13-9891-8042bca9e2ca

**Comment by LunarLanding** [comment]
> > I am on 2024.5.1, ios 17.5 does not autofill inside apps (from longpress on text field->autofill, only shows icloud), but does autofill inside safari.
> 
> Was this flow (long press > autofill) working in a previous version of the Bitwarden app?

I am not sure. I could try different password provider apps and see if any provide this flow. Any suggestions?

**Comment by micahblut** [comment]
> > > I am on 2024.5.1, ios 17.5 does not autofill inside apps (from longpress on text field->autofill, only shows icloud), but does autofill inside safari.
> > 
> > 
> > Was this flow (long press > autofill) working in a previous version of the Bitwarden app?
> 
> I am not sure. I could try different password provider apps and see if any provide this flow. Any suggestions?

I don't believe this is expected to work for any third party password providers, so I was surprised to see it mentioned.

**Comment by NextFire** [comment]
> 2024.4.2 on iOS 16.7.7, autofill suggestion doesn’t work anymore.
> 
> Video recording on [mobile.free.fr/account](https://mobile.free.fr/account/) below:
> 
>  RPReplay_Final1714974030.mp4

Same setup, last app version and still having the same issue.
I went back to iCloud Keychain.

**Comment by NextFire** [comment]
After connecting my iPhone to my Mac, I get this error in the Console when I try the autofill
```
iOS.Autofill (AuthenticationServices)
com.apple.AuthenticationServices
CredentialProviderExtension

Class CredentialProviderViewController must override -provideCredentialWithoutUserInteractionForIdentity:. Canceling extension request.
```

**Comment by 4rtz1z** [comment]
> After connecting my iPhone to my Mac, I get this error in the Console when I try the autofill
> 
> ```
> iOS.Autofill (AuthenticationServices)
> com.apple.AuthenticationServices
> CredentialProviderExtension
> 
> Class CredentialProviderViewController must override -provideCredentialWithoutUserInteractionForIdentity:. Canceling extension request.
> ```
> 
> Maybe the app is now using https://developer.apple.com/documentation/authenticationservices/ascredentialproviderviewcontroller/4172628-providecredentialwithoutuserinte which is only available on iOS 17+ while the previous versions relied on https://developer.apple.com/documentation/authenticationservices/ascredentialproviderviewcontroller/2977554-providecredentialwithoutuserinte ?

Yes i believe this is the problem, i do have this error log too while pressing the autofill button (iOS 16.5)
![IMG_6654](https://github.com/bitwarden/mobile/assets/15857763/8c2128d4-a5de-4d13-89e3-67b1d4737d71)

**Comment by LittleTurtle2333** [comment]
2024.5.2 Still not working in iOS 16.3.1

**Comment by 4rtz1z** [comment]
wohooo this fixed the issue #3282

**Comment by vvolkgang** [comment]
iOS 16 QuickType (keyboard autofill suggestions) should be fixed in our next release, thank you @NextFire and @4rtz1z for the troubleshooting info! 🙏🏾

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3225
