### ISSUE TITLE
Vault randomly stuck on loading after unlocking

### ISSUE THREAD

**Issue by antiquely8637** [bitwarden/android#3881]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Tap on a login field.
2. Unlock app with PIN or biometrics.

### Expected Result

List of saved login items is shown.

### Actual Result

App gets stuck on a loading circle.

### Screenshots or Videos

![Screenshot_20240907-104017](https://github.com/user-attachments/assets/2949fbc1-b8dd-445d-ab0a-fc6e358e53fb)

### Build Version

2024.8.1-beta (19099) 

### Environment Details

Pixel 8 Pro on Android 14.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by antiquely8637** [comment]
Found other reports of this issue
https://community.bitwarden.com/t/bitwarden-window-stuck-loading-indefinitely-when-autompleting-after-unlocking-with-pin/
https://community.bitwarden.com/t/vault-does-not-appear-after-unlocking/
https://old.reddit.com/r/Bitwarden/comments/1excplv/updated_app_sometimes_just_gets_stuck_loading/

**Comment by SergeantConfused** [comment]
Hello @antiquely8637,

Thank you for bringing this to my attention. 
1. How many matching vault items are displayed when you do unlock Bitwarden successfully?
2. Does this happen only when you unlock the vault via a PIN? Are you able to reproduce this whilst unlocking the vault via the master password or biometrics?
3. Are you logged into more than one Bitwarden account via that Bitwarden Android client?
4. Could you please detail your [KDF configuration](https://bitwarden.com/help/kdf-algorithms/)?

For added context, I am unable to reproduce this on a Pixel 5 running Android 14 with Bitwarden 2024.8.0 by attempting to perform autofill with 1 matching vault item within Chrome whilst I am logged into a single Bitwarden account.

Thank you in advance,

**Comment by antiquely8637** [comment]
Hi @SergeantConfused 

1. How many matching vault items are displayed when you do unlock Bitwarden successfully?
When it successfully unlocks, I can see all saved matching items properly. Can be 1 or more depending on the specific website. The app hangs irrespective of how many matching items are in the vault.

2. Does this happen only when you unlock the vault via a PIN? Are you able to reproduce this whilst unlocking the vault via the master password or biometrics?
Happens with both PIN and biometrics (fingerprint and face unlock).

3. Are you logged into more than one Bitwarden account via that Bitwarden Android client?
Only one account.

4. Could you please detail your [KDF configuration](https://bitwarden.com/help/kdf-algorithms/)?
Argon2id 64 MB memory, 3 iterations and 4 threads. I have tried changing back to PBKDF2 with 600 000 iterations, but that did not fix it.

**Comment by fredgolightly** [comment]
Happening here too on all devices using 2024.8.0 (18985)

**Comment by flo-m** [comment]
same here, after autofill unlocking with biometrics - only loading circle is shown. 
Force Close Bitwarden Beta 2024.8.1 and starting again brings up the vault within a second.

**Comment by dfunkt** [comment]
@SergeantConfused: Managed to get some logs for you
```
09-11 19:29:50.395 22330 22330 E ActivityImpl: get life cycle exception
09-11 19:29:50.395 22330 22330 E ActivityImpl: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to android.app.servertransaction.ClientTransaction
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityImpl.checkAccessControl(ActivityImpl.java:64)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityImpl.onResume(ActivityImpl.java:140)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.Activity.onResume(Activity.java:2128)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at i.i.onResume(Unknown Source:5)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1592)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.Activity.performResume(Activity.java:8741)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5079)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5122)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:64)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6064)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.os.Looper.loopOnce(Looper.java:211)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.os.Looper.loop(Looper.java:300)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at android.app.ActivityThread.main(ActivityThread.java:8503)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
09-11 19:29:50.395 22330 22330 E ActivityImpl: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
09-11 19:29:50.397  4743  4743 W RecentsImpl: onResumed className=com.x8bit.bitwarden.MainActivity   mIsInAnotherPro=false   isKeyguardLocked=false   mSecuritySpaceGuideShown=false
09-11 19:29:50.398  4743  4830 W RecentsImpl: disableTouchBySwipeStatusBar    disable=false
09-11 19:29:50.398  4743  4830 W RecentsImpl: disableBackStubWindow    disableTouch=false
```

**Comment by Issam28** [comment]
@SergeantConfused, I can reproduce this bug following these steps:

1. Open the bitwarden vault and keep the app oppened in the background.
2. Go to chrome and auto fill from any website
3. The vault will hang forever.

For testing purposes, I set the vault timer to "immediately" but the bug can be reproducible by any timer. I'm using a Pixel 8 on Android 15 beta.

Here's a video that shows how it works.

https://github.com/user-attachments/assets/535f9c59-2d5f-4429-9837-cb67d6adab68

**Comment by dragm83** [comment]
Same issue on a Galaxy S23 Ultra running 2024.8.1 (beta).

**Comment by MillionsToOne** [comment]
+1

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. I was able to reproduce this now on a Pixel 5 running Android 14 with Bitwarden 2024.8.1, and have highlighted this internally to the Engineering department. Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you all again,

**Comment by johnkennyuk** [comment]
Also affected by this bug.

**Comment by SohamJ** [comment]
One workaround I've been using is to open the app again and then go back to autofill. That avoids the need to force close the app.

**Comment by antiquely8637** [comment]
Just tried a clean install of 2024.9.0 (19209). Bug still there.

**Comment by flo-m** [comment]
What works for me as a temporary workaround ist to set the Energy saving feature for bitwarden app to max - so that the App will be closed instantly.
Then Autofill works fine and the bug ist Not there...

**Comment by ghanjiboy** [comment]
I am also experiencing the same issue.  I have only had the beta installed since around September 10th.   This spinning behavior wasnt happening then, but started happening about a week or so ago.  I am experiencing the same as others above with spinning right after initiating autofill and unlocking.

If I unlock the app and then goto autofill, everything works, the app opens and presents the handful of choices.

I am running 9.0 as well.

**Comment by laxmanpradhan** [comment]
I have the same issue on 2024.9.0 installed via obtainium on a google pixel 8.

I'm connecting to a self hosted vaultwarden if that matters. Happy to update with logs, I just don't know how to get logs for the android app

**Comment by Bims-sh** [comment]
Same problem here on 2024.9.0, Android 15

Opening the app from my home menu and going back to auto-fill in my browser makes it load and work for some time :+1:

**Comment by laxmanpradhan** [comment]
FWIW clearing the cache and relogging into the all fixed it for now. I'll report back on if it happens again. Could be an errorbthag takes a few days to show up

**Comment by ralob** [comment]
> > App Version 2024.9.0 still an issue. Did find if I open/unlock Bitwarden first then go to app and use autofill it will search properly with out just sitting there spinning.
> 
> I can confirm this behaviour (same app version).
> 
> In addition, after attempting to open for autofill, using fingerprint, and getting to spinning circle, if I then back out to the page I'm trying to fill, then open BW normally, it opens and is unlocked (i.e. the previous fingerprint succeeded).
> 
> Then, back on the page I want to fill, I can open for autofill and there is no delay.

This is the same thing I experience with Android 14 and BW version 2024.9.0 (19209). 

Additionally, sometimes I have to force close BW and reopen it to get autofill to work for the page I'm on.

**Comment by bluearcher-bc** [comment]
> Additionally, sometimes I have to force close BW and reopen it to get autofill to work for the page I'm on.
@ralob switch from your browser/app you are trying to auto fill over to Bitwarden, then do a sync on the vault, then switch back to the app

**Comment by Bims-sh** [comment]
> Same problem here on 2024.9.0, Android 15
> 
> Opening the app from my home menu and going back to auto-fill in my browser makes it load and work for some time 👍

For the past week this problem somehow went away for no reason, I have not changed any settings on my phone that could have fixed this as far as I'm aware.

**Comment by niikoo** [comment]
> > Additionally, sometimes I have to force close BW and reopen it to get autofill to work for the page I'm on.
> 
> @ralob switch from your browser/app you are trying to auto fill over to Bitwarden, then do a sync on the vault, then switch back to the app

This works as a workaround, but it's very annoying that I have to do that all the time.

Currently running Bitwarden version 2024.9.0 (19209) on Android 15 QPR Beta 2 (Pixel 6).

**Comment by leo-liar** [comment]
Problem unfortunately still not fixed with recently released stable build 2024.10.1 ...

(As workaround I'm doing what bluearcher-bc recommended a few days ago.)

**Comment by ghanjiboy** [comment]
With the latest beta and now the official release, both are now working as expected for me.

**Comment by maszaa** [comment]
Exists in 2024.10.2 which seems to be the latest official version.

**Comment by Ices-Eyes** [comment]
Hi, same problem here with the official version released this days 2024.10.2 on Oneplus Nord 2 with android 13.

**Comment by RickPJ** [comment]
I'm now on 2024.90, and the autofill tile doesn't work at all. Even when on a field and URL for which I know BW has an entry, tapping the tile does nothing. Force closing BW doesn't fix it.
FairPhone 3, AOS 11

**Comment by masterflitzer** [comment]
@RickPJ can you try on 2024.10.1 or even 2024.10.2? it's fixed for me currently (no problems for 1 day)

**Comment by MillionsToOne** [comment]
> @RickPJ can you try on 2024.10.1 or even 2024.10.2? it's fixed for me currently (no problems for 1 day)

I believe it will be mentioned in the changelog once it's fixed.

**Comment by MillionsToOne** [comment]
> Where can I download the APK? Currently I'm just getting beta updates from the Play store, latest there is 2024.9.0

Github releases

**Comment by jannispl** [comment]
Can confirm the issue still exists in 2024.10.2 (and current `main` branch at c2537f329d573209f065138cd37dd151471ee912).

**Comment by flo-m** [comment]
Maybe you guys use vaultwarden?

**Comment by dfunkt** [comment]
It's just not fixed yet, there's a PR in progress for it -> https://github.com/bitwarden/android/pull/4214

**Comment by pcartwright81** [comment]
> Maybe you guys use vaultwarden?
Not sure why this suggestion was thumbs-downed.  In reality I have dealt with this bug for at least the last 3 months on the beta version, and now it has been released to the masses.  This is a breaking issue for me because I can not rely on my phone to work correctly.  I try to auto fill and get stuck in this loop that requires killing the app multiple times.  I could have gone back to the stable version before, but the issue would catch up sooner or later, and I didn't realize it would take 3 months to fix.

Currently I am looking into vaultwarden or a self hosted instance with a client version that I know to be stable.

This was especially fueled by the fact that I had to clear storage as soon as version 2024.11.0 was installed today because of an app crash.

**Comment by NotoriousNico** [comment]
I have the exact same issue on all of my devices (for example my Samsung Galaxy S24 Ultra running Android 14).

I'm using Version: 2024.10.2 (19397) and have not a self-hosted Bitwarden instance. The issue happens also regardless of what browser or App I'm using.

In its current state, Bitwarden for Android is almost useless for me, and I'm quite perplexed that this issue made it into Stable.

I hope this gets resolved soon.

**Comment by dannyglover** [comment]
Version 2024.11.0 (19421) seems to have made this issue occur even more frequently. 

I'm really hoping that the issue is fixed soon, as it's quite infuriating. 

Thank you.

**Comment by fredgolightly** [comment]
This is happening even more with the newest Play Store update on all my and my family devices, absolutely unusable now especially for those without much tech knowhow as it requires closing BW, opening the app settings, force closing it, reopening the app/website then BW.

**Comment by bluearcher-bc** [comment]
@RickPJ don't get ahead of yourself, the PR that should resolve this is still open. This issue doesn't always show up right away after an update.

**Comment by Secunda-Moon** [comment]
Thought something wrong with my internet connection, but things turned out that it is a widely-encountered software bug. I'm still experiencing this problem with the latest beta version. Tried the regular version, and the problem remains.

Hope the developer can fix the bug.

**Comment by maxmini1** [comment]
Seems that the issue its still there Version: 2024.11.1 (19422) its work if you " set session timeout "  to 1 or higher no't Immediately,
 " On the same thing to passkey "
![Screenshot_20241106_135010_Bitwarden](https://github.com/user-attachments/assets/a1882ad6-96a7-4747-88e3-edf683387cde)
See the screenshot below

![Screenshot_20241106_134745_Bitwarden](https://github.com/user-attachments/assets/b7c0eca0-696e-4b46-962d-dc9af8264168)
![Screenshot_20241106_134702_Bitwarden](https://github.com/user-attachments/assets/a887747f-b1ff-4e16-b0de-b23566fa4e7a)
![Screenshot_20241106_134950_Bitwarden](https://github.com/user-attachments/assets/a155c169-4e30-48f1-b4c3-3f17d7deb5b8)

**Comment by dfunkt** [comment]
For those that can't wait for an update, there are builds available now with commit ec85e7af619a755720f91caaef994a7913919325 that appears to fix this behaviour -> https://github.com/bitwarden/android/actions/runs/11712269067

**Comment by maxmini1** [comment]
> For those that can't wait for an update, there are builds available now with commit [ec85e7a](https://github.com/bitwarden/android/commit/ec85e7af619a755720f91caaef994a7913919325) that appears to fix this behaviour -> https://github.com/bitwarden/android/actions/runs/11712269067

@dfunkt Hi here thank you su much for the update its seem to have fixed on Version: 2024.11.2 (19430. new its work perfect keep up the great work!
 
https://github.com/user-attachments/assets/8f39afee-b2f1-4975-ba8a-b2d790501acb

**Comment by YamiYukiSenpai** [comment]
When will that update get pushed to the stable or beta version in F-Droid?

**Comment by MillionsToOne** [comment]
When next release comes.

**Comment by MillionsToOne** [comment]
Should be obvious.

**Comment by pcartwright81** [comment]
I think it should be obvious that the question was not for the users of the app like us, but the developers of the app.  Considering they are the ones that pushed a high profile bug to the stable version.

**Comment by maxmini1** [comment]
@MillionsToOne 
> sounds like its there new
https://github.com/bitwarden/android/releases/tag/v2024.11.2

**Comment by maxmini1** [comment]
> When next release comes.
@MillionsToOne 
Sounds like its there new
https://github.com/bitwarden/android/releases/tag/v2024.11.2

**Comment by maxmini1** [comment]
@dfunkt i see that the issue its have ben fixed su you should close it https://github.com/bitwarden/android/releases/tag/v2024.11.3

**Comment by dfunkt** [comment]
@maxmini1: I'm not the one who opened this issue, @antiquely8637 is.

**Comment by SaintPatrck** [comment]
Hi all,
As mentioned in other comments, this has been addressed in release 2024.11.3, which is now generally available in PlayStore and our F-Droid repository.
