### ISSUE TITLE
Generator: Unnecessary linebreaks for long passwords

### ISSUE THREAD

**Issue by Jan-Koll** [bitwarden/android#4166]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to 'Generator'
2. Increase password length via the slider

### Expected Result

The generated password fills the available horizontal space.

### Actual Result

Unnecessary linebreaks are added almost every other line. This results in a lot of vertical space that is required.

### Screenshots or Videos

![Screenshot_2024-10-25-19-02-32-79_edf9c6c5202cf0aae90965d36a8e7fc4](https://github.com/user-attachments/assets/a8827af9-364f-4007-9719-e88c2b8f9344)

### Build Version

2024.9.0 (19209)

### Environment Details

Android 12, default system font size

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by differsthecat** [comment]
This was fixed by [this PR](https://github.com/bitwarden/android/pull/4187), closing 🙂

**Comment by vinnyperella** [comment]
This is still an issue in 2024.10.2 what version will the fix be implemented in?

**Comment by vinnyperella** [comment]
> This was fixed by [this PR](https://github.com/bitwarden/android/pull/4187), closing 🙂 

This is still an issue in 2924.10.2 what version will the fix be implemented in?

**Comment by Jan-Koll** [comment]
I agree, the issue is still there in the latest beta (Version: 2024.10.2 (19397)). Although for me there are now 3 characters every other line instead of one.

**Comment by Jan-Koll** [comment]
@differsthecat @jtodddd Maybe this issue could be opened again, since the problem doesn't seem to be resolved.

> Just an update, up until 11.2 it was showing regular linebreaks (alternative lines with just 2 characters) as shown in the posted screenshot. In 11.3 and 11.4 it is showing random linebreaks as in the "before" video of the posted pull request #4187.

Interesting. I am on 11.3 currently and I always get 3 characters every other line.

By the way, I just noticed this is also the case for the passphrase generation (so not only password generation).

**Comment by Jan-Koll** [comment]
In 2024.11.6 (19499) it is fixed.

**Comment by vinnyperella** [comment]
> In 2024.11.6 (19499) it is fixed.

This still looks to be an issue in the Bitwarden native Android app 2025.1.0. Sometimes it lines up correctly but other times it does what I've shown below.

![Image](https://github.com/user-attachments/assets/7046965e-b6dc-4c58-aca3-02e81b941bb4)
