### ISSUE TITLE
Passkeys can not be retrieved / verified

### ISSUE THREAD

**Issue by profpepper58** [bitwarden/android#4582]
### Production Build

- [x] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Use passkey to unlock accounts (happens on my banking app and also Github). 
2. Unlock vault with biometrics OR password. 
 

### Expected Result

Passkey successfully unlocks account. 

### Actual Result

Get error "Passkey operation failed because user could not be verified" followed by "we were unable to process your request. Please try again or contact us"

### Screenshots or Videos

Cannot screenshot the app

### Additional Context

Passkeys used to work about a week ago. 

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy A35 5G

### Build Version

2025.1.0

**Comment by profpepper58** [comment]
Hi,

I tested it on githib in mobile Firefox browser (134.0.1) the github app (1.192.0), and my banking app which is ubank (11.91.0) in Australia. If you'd like me to test the passkey somewhere else let me know. 

Thanks.

**Comment by nategasm** [comment]
Can confirm getting the same issue on the uBank app. The app just constantly says "Something went wrong" when trying to login with the passkey. It also doesn't even detect standard passwords no matter how many new entries you add.

**Comment by BakedCrossiant** [comment]
Before it says "Something went wrong" it also says that the "user cannot be verified". Tested on Pixel 6.

**Comment by vrbt150** [comment]
Same issue as @nategasm. Running Android 14 on Samsung Galaxy S24 FE. Legacy app worked fine tho.

Also noticed an issue in WhatsApp when trying to create a passkey with Bitwarden. Bitwarden seems to create it, but WhatsApp doesn't realise it has been created.

**Comment by RupertMichaelBear** [comment]
Just to add to t his, same issue with my Galaxy S22u and my Australian banking App (Ubank).  Worked until the recent Bitwarden update. Still using email for 2FA here

**Comment by vrbt150** [comment]
Just upgraded to 2025.1.1 and issue is still persistent

**Comment by SaintPatrck** [comment]
Hi all. We're still investigating the issue with uBank and will provide an update as soon as we have more information.

Regarding the WhatsApp problem: I believe this is a bug on WhatsApp's end. 

I was able to replicate passkey creation failure when registration is triggered from the Settings screen in WhatsApp. There are no logs indicating anything is wrong on our end during this process. WhatsApp appears to silently fail when it receives our response. 

**However**, if you choose to create a passkey while signing in to WhatsApp for the first time, registration completes on our end and WhatsApp accepts the response. Navigating to Settings > Passkeys, you can see the passkey was successfully registered in WhatsApp's system. Unfortunately there's nothing more we can do on our end at this time to improve the WhatsApp behavior. I suggest reaching out to WhatsApp and informing them of this issue if you're able to replicate it as consistently as I was.

**Comment by BJReplay** [comment]
> Hi all. We're still investigating the issue with uBank and will provide an update as soon as we have more information.

Hi @SaintPatrck, issue #3866 provides additional information about the issue with UBank, including screenshots, and that Bitwarden legacy **does work**, KeyGuard **does work**, but that Bitwarden native (tested right up to:
© Bitwarden Inc. 2015-2025

Version: 2025.1.1 (19728)
📱 samsung SM-S908E 🤖 14@34 📦 beta
local) **does not**, all accessing the same passkey in the same vault.

**Comment by vrbt150** [comment]
> Hi all. We're still investigating the issue with uBank and will provide an update as soon as we have more information.
> 
> Regarding the WhatsApp problem: I believe this is a bug on WhatsApp's end.
> 
> I was able to replicate passkey creation failure when registration is triggered from the Settings screen in WhatsApp. There are no logs indicating anything is wrong on our end during this process. WhatsApp appears to silently fail when it receives our response.
> 
> **However**, if you choose to create a passkey while signing in to WhatsApp for the first time, registration completes on our end and WhatsApp accepts the response. Navigating to Settings > Passkeys, you can see the passkey was successfully registered in WhatsApp's system. Unfortunately there's nothing more we can do on our end at this time to improve the WhatsApp behavior. I suggest reaching out to WhatsApp and informing them of this issue if you're able to replicate it as consistently as I was.

Hi, just to add, passkeys worked on WhatsApp with Bitwarden legacy and all other password managers I have tested with (1Password, Proton Pass, and Google Password Manager). Regardless, I will contact WhatsApp as suggested. Thanks

**Comment by SaintPatrck** [comment]
Hi @BJReplay 

I did see all of the details included in that issue. I appreciate everyone taking the time to capture all of the information. It helped eliminate some potential causes.

I believe I have good lead on the issue and it is potentially spawning from our SDK. The legacy application does not use our SDK, which would explain why it works and the native app does not. However, I'm not able to prove that theory without having an account with uBank and I cannot create one since I'm not an AUS citizen. 

I opened #4694 which, among other things, improves user facing error messages so we can hopefully identify where exactly the process is failing. If you or anyone else tracking this issue are willing to assist, using a build from that PR and reporting back the results would be a great start.

If my theory is correct I expect that the failure is occurring [here](https://github.com/bitwarden/android/pull/4694/files#diff-d4af48c048c6642a91a4ea480d3ed4b4e1363da7afd0e51318bd42ec867c2541R85) due to an RpOriginMissmatch error from the SDK.

**Comment by SaintPatrck** [comment]
Hi @vrbt150 

Thanks for the additional info. Did you happen to try creating a passkey during initial sign in? If so, was it successful? 

What's really odd to me about the WhatsApp behavior is that there is no failure during our processing like there is with UBank, or you would see dialogs in Bitwarden. That's the only reason I suggest it may be something on their end. They may be able to debug and pinpoint why it's rejecting our response. Keep us updated on WhatsApps response. I'm happy to continue investigating if more details arise.

**Comment by BJReplay** [comment]
> If you or anyone else tracking this issue are willing to assist

On it.  Will report back.

**Comment by BJReplay** [comment]
> On it. Will report back.

No luck.  the build didn't complete, so there are no assets for me to install, and I don't think I have the ability to set up an environment to do a build.

**Comment by BJReplay** [comment]
© Bitwarden Inc. 2015-2025

Version: 2025.2.0 (19770)
📱 samsung SM-S908E 🤖 14@34 📦 beta
🧱 commit: bitwarden/android/PM-11886/update-origin-for-unprivileged-apps@962de84eeafe4fe991dd8ffc6cecc2c2a9267c90
💻 build source: bitwarden/android/actions/runs/13149534226/attempts/1

I love the copy paste version, by the way!

No luck - same errors as I believe I previously reported at #3866 - I didn't recognise anything different.  Sorry about the dodgy photos - screenshots blocked by Ubank (even if enabled for Bitwarden)

PII redacted by the generative erase in the Microsoft Photos app in Win11.  It's actually remarkably good for that.

![Image](https://github.com/user-attachments/assets/6cff3b6f-bb9f-41b3-9056-5f5c62441c65)

![Image](https://github.com/user-attachments/assets/6fcc0819-9e8c-44e7-9985-71776b8a13b6)

![Image](https://github.com/user-attachments/assets/ab5334b1-d3c8-41d3-9f7b-9d54549f03f7)

![Image](https://github.com/user-attachments/assets/bdab88f6-c762-4273-a121-f024ca0e27c8)

![Image](https://github.com/user-attachments/assets/565f7b51-6b27-44c2-a885-6e45139b33da)

**Comment by profpepper58** [comment]
Any update on this?

**Comment by SaintPatrck** [comment]
@vrbt150 Thanks for checking back in.

With regards to Paypal, that is known and expected. Paypal has not configured their assetlinks.json correctly to support passkeys from their native Android application. [This comment](https://github.com/bitwarden/android/issues/4222#issuecomment-2631615898) has more details about the PayPal implmenetation.

We have connected with the UBank team and are actively working on the issue. Updates will be provided as they are available. I appreciate everyone's patience as we work to find a resolution.

**Comment by vrbt150** [comment]
> [@vrbt150](https://github.com/vrbt150) Thanks for checking back in.
> 
> With regards to Paypal, that is known and expected. Paypal has not configured their assetlinks.json correctly to support passkeys from their native Android application. [This comment](https://github.com/bitwarden/android/issues/4222#issuecomment-2631615898) has more details about the PayPal implmenetation.
> 
> We have connected with the UBank team and are actively working on the issue. Updates will be provided as they are available. I appreciate everyone's patience as we work to find a resolution.

I do remember this with PayPal, not sure if a recent update has changed this as I can create a passkey and login to PayPal with Proton Pass without issue.

**Comment by BakedCrossiant** [comment]
This also happens with the discord android app.

**Comment by SaintPatrck** [comment]
Hi all,

I'm happy to share that UBank issues are resolved with #4694. It will be in the 2025.2.0 release. 

We also received confirmation from Google that we can safely relax digital asset link validation. As a result #4804 will resolve failures related to "app not found in asset links" errors. This includes PayPal and several other applications. This fix will not be in 2025.2.0 but should be in the following release.

And last, but not least, WhatsApp has confirmed they're aware of an issue with passkeys on their end. Once we receive an update we will make any changes necessary, but hopefully it will simply start working soon. 

Given that the primary issue in this thread was with UBank and PayPal, I'm going to close it. If anyone continues having problems with UBank after the 2025.2.0 release let me know and we can re-open this issue. If you experience problems with other applications, please open a new issue with details specific to that application. This will help us better organize and triage issues on a app-by-app basis.

Thank you all for your assistance, and most importantly, your patience while we work though these issues. 🫶

**Comment by cipavlou** [comment]
I'm still seeing this with 2025.2.0 and latest ubank app version.  
When I try and log in, I go into an endless loop of unlocking Bitwarden and, when I exit the loop, get "no credentials available for login"

**Comment by BJReplay** [comment]
> I'm still seeing this with 2025.2.0 and latest ubank app version.

@cipavlou I was able to log into Ubank Almost immediately after I upgraded.

What I did (_in no particular order_) before attempting to log into Ubank was:
- made sure that Bitwarden was set up for Auto-fill, passkeys, and default passkey.
To do that, I had to log in.
- Checked that Bitwarden was responding to passkey requests with test logins at https://www.passkeys.io/ and https://www.passkeys-debugger.io
- Logged in to Ubank.

Perhaps the difference was that
- I had logged into Bitwarden, and
- I don't have an immediate lock set, so it was still unlocked.

It could be worth checking when you unlock Bitwarden first (and ensure that you don't have a lock immediately set-up) to see if that fixes the problem.

If it does, that might mean that there is a bug in the steps that respond to a passkey request and unlock the vault.

Having said that, I just tried with my vault locked via the lock time out and I got three prompts from Bitwarden (and one from the OS) after starting the login from Ubank:
1. Choose Passkey provider (I still have the beta build installed) 
2. Unlock (biometrics) Bitwarden 
3. Select Ubank Passkey
4. Authenticate (biometrics)

**Comment by cipavlou** [comment]
Thanks.  It turns out that biometrics/fingerprint unlock was causing Bitwarden to crash on my phone.  Using Bitwarden without biometrics is fine/passkey works

**Comment by SaintPatrck** [comment]
Hi @cipavlou 

I'm glad to hear passkeys are working for you now. 

Just so you're aware, we've identified the issue with biometrics and are working on a solution. We hope to have it included in the next release. I've re-opened https://github.com/bitwarden/android/issues/4659, so keep an eye out for updates to the biometrics issue there.
