### ISSUE TITLE
[PM-29303] Cloudflare Proxy Causing Trust Chain Issues

### ISSUE THREAD

**Issue by crespire** [bitwarden/android#6242]
### Steps To Reproduce

I'm self hosting via vaultwarden, but this problem has recently cropped up.

I have a vaultwarden instance behind a Cloudflare proxy.
Basically, I get the error:
> **An error has occured**
> We couldn't verify the server's certificate. The certificate chain or proxy settings on your device or your Bitwarden server may not be set up correctly.

I don't get this server on the same device when using the web vault, and on other devices I don't get any issues with the official browser extension, so it seems I only have an issue with the Android app.

### Expected Result

Be able to log in and do stuff on my mobile app.

### Actual Result

Unable to log in.

### Additional Context

Running the latest vaultwarden behind a Cloudflare proxy. SSL Certifcate checkers I've tried (Comodo, and Digicert) both report checkmarks and show the full chain is correctly configured. On Digicert, the only warning is the issuer because my issuer is Cloudflare and not one of their trusted issuers.

This issue recently cropped up, so I think it's been something in November that surfaced this issue.

I've looked around and found github.com/bitwarden/mobile/issues/1657 but it's long since been closed. This is a reference to the first issue, also closed: https://github.com/bitwarden/android/issues/1657

### Build Version

Android 2025.11.0 (20967)

### What server are you connecting to?

Self hosted

### Self-host Server Version

Vaultwarden 1.34.3

### Environment Details

Device is a Pixel 7a running the latest OS version (Android 16, build BP3A.251105.015).

Server is running via docker, with all up to date images behind a Caddy reverse proxy.

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pamperer562580892423** [comment]
Another user here.

> Steps To Reproduce
> I'm self hosting via vaultwarden, but this problem has recently cropped up.
> ...
> Self-host Server Version
> Vaultwarden 1.34.3

Some words of advice for you: either try to reproduce your issue with a Bitwarden server - or report this to Vaultwarden. (or both)

**Comment by crespire** [comment]
I can at least confirm it's a Cloudflare proxy issue - turning off the proxy resolves my problem.

**Comment by crespire** [comment]
For those also running into this, there seemed to be some internal issue with SSL certificates issued via CF that was resolved. I think messing with the proxy settings caused a re-issue or I was otherwise already close to renewal, but turning it off and on again seemed to resolve the issue for me.

**Comment by robinsonkw** [comment]
I can confirm that this issue still happens with bitwarden.com, even with excluding the domain via Cloudflare split-tunnels.  It would be a great feature to be able to force Cloudflare on a work profile, and allow Bitwarden to work.
